### PR TITLE
home: added links to the footer and screenshot

### PR DESCRIPTION
**Pull request by fries1234**
i added matrix and open collective links to the footer and added a screenshot to Automatic Backups and capitalised the A in Arch

### CODE REVIEW

**Comment by fries1234** [comment]
ok im gonna uh rebase this to main since development seemed to be messed up

**Comment by fries1234** [comment]
ok updated the docs submodule here :+1:

**Comment by mrshmllow** [comment]
no... why..  stop

**Comment by fries1234** [comment]
ok i reverted it im very sorry

**Pull request closed without merging**
