### PR TITLE
NextJS

### PR DESCRIPTION
**Pull request by mrshmllow**
- [x] Init
- [x] Theming (dark/light mode)
- [x] Responsive navbar
- [x] Seo
- [x] md(x ?)
- [x] /docs
- [ ] /blog
- [ ] Server side contribution and languages list
- [ ] Feat parity with main (/team etc)

### CODE REVIEW

**Comment by mrshmllow** [comment]
please don't merge to development until I get to atleast the next 5 goals

**Comment by not-my-segfault** [comment]
Understood, it's a Draft currently so we won't until you mark it as open :+1:

**Comment by mrshmllow** [comment]
we should definitely squash these

**Comment by 0xMRTT** [comment]
@mrshmllow do you need help on that ?

**Comment by not-my-segfault** [comment]
It'd be useful to make sure our Forum (https://forum.getcryst.al) is linked on the website too

**Comment by mrshmllow** [comment]
it already is

**Comment by not-my-segfault** [comment]
Alright, no worries then, just making sure

**Comment by mrshmllow** [comment]
this is about the WORST code ive ever written. its super hacky

**Comment by not-my-segfault** [comment]
Would we say this is ready to merge now?

**Comment by mrshmllow** [comment]
yes

**Review by not-my-segfault — APPROVED** [review]

**Comment by mrshmllow** [comment]
i should probably start charging for weeks of work

**Comment by not-my-segfault** [comment]
I'll shuffle some stuff around to get infra ready, then I'll merge

**Comment by mrshmllow** [comment]
oh rip

**Comment by not-my-segfault** [comment]
Lol it's ok I managed to do what I needed to do in time

**Pull request merged**
