### PR TITLE
Add Swedish Translation

### PR DESCRIPTION
**Pull request by bittin**
by: lunajernberg@gnome.org

### CODE REVIEW

**Comment by mrshmllow** [comment]
please add it to next-i18next.config.js

**Comment by bittin** [comment]
@mrshmllow done so now

**Review by mrshmllow — APPROVED** [review]

**Comment by mrshmllow** [comment]
ty! great job

**Comment by mrshmllow** [comment]
seems you forgot a comma

**Comment by bittin** [comment]
> seems you forgot a comma

fixed

**Pull request merged**
