### PR TITLE
Cleanup deadcode and style 

### PR DESCRIPTION
**Pull request by mrshmllow**

### CODE REVIEW

**Comment by mrshmllow** [comment]
Dear god who wrote this react code

**Review by kketg — COMMENTED** [review]
So there are parts of this that I like and parts that I'm a little confused about. 

I think that removing the container tags in the index file is a good idea, removing the margin from the cards and the redundancy with the highlight-header and highlight-text tags is good. Generally a lot of the cleanup is great.

The parts I'm concerned about are specifically the changes to the header/navbar, and the intro text. I may have missed something, but when I tried to check the styling, the new CSS looked odd to me. A lot of the margin placement I had for the intro text was to prevent the page from looking cramped and overtaken by the cards, which is what I think it looks like with this styling. The shrinking of the header that reads "An Arch Based Distribution" also bothers me.  

I also don't really get the need to remove the Home button and navbar:hover styling (I think this is a subjective preference rather than a styling issue). I may just have missed the intention with it, and I'm still willing to change it if it really is a problem.

Also, yeah I know the react code is a mess. I didn't want to do it with all the JSX and everything until I was sure how the site was going to be deployed.

**Review by kketg — APPROVED** [review]
The favicon is good and fine.

**Comment by mrshmllow** [comment]
tile shrinking was a mistake.

generally a header should only darken when the user is scrolled further down the screen

"home" was removed because there is already a "Crystal Linux" button (see: every website ever)

what was the highlight class for?

**Comment by kketg** [comment]
The highlight class in theory was meant to be a container for what's being showcased front and center on the page, which is why I used it for the margin and such. I'm also good with removing the home button from the navigation.

As for your comment about the header darkening, that would make sense if the header was sticky, but as it is it stays at the top of the page. In my design theory for it, it would blend with the rest of the site until it was "being used" so to speak, hence the darkening when hovered over. I'd be happy to implementing a sticky header that darkens when scrolling down, but we should probably make that it's own separate commit lol, as that'd be more involved with JS and stuff rather than just minor style changes.

**Review by kketg — APPROVED** [review]
So I will approve this PR at this point, and I'm gonna start working on a separate update to the website which will address some of the things I point out in my last comment. Thanks a lot for the cleanup and for the cooperation! (I will definitely also get to work on cleaning up the react code lmao)

**Review by not-my-segfault — APPROVED** [review]

**Comment by hericiumvevo** [comment]
LGTM

**Comment by mrshmllow** [comment]
Please never merge commit!! Rebase :(

**Comment by not-my-segfault** [comment]
Sorry!! 🙇 I'm currently away from home and didn't know that was the default behaviour on GitHub mobile

**Comment by mrshmllow** [comment]
❤️❤️

**Pull request merged**
